#ifndef CONFIGCOMMAND_H
#define CONFIGCOMMAND_H

#include <CuteCommand.h>
#include <iostream>
#include <vector>
#include <exception>
#include <string>

using std::vector;
using std::to_string;

namespace Drone
{
    namespace Command
    {
        class CONFIGCommand : public CuteCommand
        {
        public:
            enum class ConfigType : int{
                NUM_VERSION_CONFIG           ,
                NUM_VERSION_MB               ,
                NUM_VERSION_SOFT	         ,
                DRONE_SERIAL    	         ,
                SOFT_BUILD_DATE 	         ,
                MOTOR_1_SOFT    	         ,
                MOTOR_1_HARD    	         ,
                MOTOR_1_SUPPLIER	         ,
                MOTOR_2_SOFT    	         ,
                MOTOR_2_HARD    	         ,
                MOTOR_2_SUPPLIER	         ,
                MOTOR_3_SOFT    	         ,
                MOTOR_3_HARD    	         ,
                MOTOR_3_SUPPLIER	         ,
                MOTOR_4_SOFT    	         ,
                MOTOR_4_HARD    	         ,
                MOTOR_4_SUPPLIER	         ,
                ARDRONE_NAME    	         ,
                FLYING_TIME     	         ,
                NAVDATA_DEMO    	         ,
                NAVDATA_OPTIONS 	         ,
                COM_WATCHDOG    	         ,
                VIDEO_ENABLE    	         ,
                VISION_ENABLE   	         ,
                VBAT_MIN        	         ,
                ACCS_OFFSET     	         ,
                ACCS_GAINS       	         ,
                GYROS_OFFSET    	         ,
                GYROS_GAINS     	         ,
                GYROS_110_OFFSET             ,
                GYROS_110_GAINS              ,
                MAGNETO_OFFSET               ,
                MAGNETO_RADIUS               ,
                GYRO_OFFSET_THR_X            ,
                GYRO_OFFSET_THR_Y            ,
                GYRO_OFFSET_THR_Z            ,
                PWM_REF_GYROS                ,
                OSCTUN_VALUE                 ,
                OSCTUN_TEST                	 ,
                ALTITUDE_MAX                 ,
                ALTITUDE_MIN                 ,
                CONTROL_LEVEL                ,
                EULER_ANGLE_MAX              ,
                CONTROL_IPHONE_TILT          ,
                CONTROL_VZ_MAX               ,
                CONTROL_YAW                	 ,
                OUTDOOR                		 ,
                FLIGHT_WITHOUT_SHELL         ,
                AUTONOMOUS_FLIGHT            ,
                MANUAL_TRIM                	 ,
                INDOOR_EULER_ANGLE_MAX       ,
                INDOOR_CONTROL_VZ_MAX        ,
                INDOOR_CONTROL_YAW           ,
                OUTDOOR_EULER_ANGLE_MAX      ,
                OUTDOOR_CONTROL_VZ_MAX       ,
                OUTDOOR_CONTROL_YAW          ,
                FLYING_MODE                	 ,
                HOVERING_RANGE               ,
                FLIGHT_ANIM                	 ,
                SSID_SINGLE_PLAYER           ,
                SSID_MULTI_PLAYER            ,
                WIFI_MODE                	 ,
                WIFI_RATE                	 ,
                OWNER_MAC                	 ,
                ULTRASOUND_FREQ              ,
                ULTRASOUND_WATCHDOG          ,
                PIC_VERSION                	 ,
                CAMIF_FPS                	 ,
                CODEC_FPS                	 ,
                CAMIF_BUFFERS                ,
                NUM_TRACKERS                 ,
                VIDEO_CODEC                	 ,
                VIDEO_SLICES                 ,
                VIDEO_LIVE_SOCKET            ,
                VIDEO_STORAGE_SPACE          ,
                BITRATE                		 ,
                MAX_BITRATE                	 ,
                BITRATE_CTRL_MODE            ,
                BITRATE_STORAGE              ,
                VIDEO_CHANNEL                ,
                VIDEO_ON_USB                 ,
                VIDEO_FILE_INDEX             ,
                LEDS_ANIM                	 ,
                ENEMY_COLORS                 ,
                GROUNDSTRIPE_COLORS          ,
                ENEMY_WITHOUT_SHELL          ,
                DETECT_TYPE                	 ,
                DETECTIONS_SELECT_H          ,
                DETECTIONS_SELECT_V_HSYNC    ,
                DETECTIONS_SELECT_V          ,
                OUTPUT                		 ,
                MAX_SIZE                	 ,
                NB_FILES                	 ,
                USERBOX_CMD                	 ,
                LATITUDE                	 ,
                LONGITUDE                	 ,
                ALTITUDE                	 ,
                APPLICATION_ID               ,
                APPLICATION_DESC             ,
                PROFILE_ID                	 ,
                PROFILE_DESC                 ,
                SESSION_ID                	 ,
                SESSION_DESC
            };

            CONFIGCommand(ConfigType configType, QString valueString);
            CONFIGCommand(ConfigType configType, int valueInt);
            CONFIGCommand(ConfigType configType, float valueFloat);
            CONFIGCommand(ConfigType configType, double valueDouble);
            CONFIGCommand(ConfigType configType, vector<int> valueIntArray);
            CONFIGCommand(ConfigType configType, vector<float> valueFloatArray);
            CONFIGCommand(ConfigType configType, bool valueBool);
            ~CONFIGCommand();
            QString getCommand() override;
            bool operator ==(CuteCommand* t) const;

        private:

            ConfigType configType;
            QString value;

            vector<QString> toString = { "\"general:num_version_config\"",
                                        "\"general:num_version_mb\"",
                                        "\"general:num_version_soft\"",
                                        "\"general:drone_serial\"",
                                        "\"general:soft_build_date\"",
                                        "\"general:motor1_soft\"",
                                        "\"general:motor1_hard\"",
                                        "\"general:motor1_supplier\"",
                                        "\"general:motor2_soft\"",
                                        "\"general:motor2_hard\"",
                                        "\"general:motor2_supplier\"",
                                        "\"general:motor3_soft\"",
                                        "\"general:motor3_hard\"",
                                        "\"general:motor3_supplier\"",
                                        "\"general:motor4_soft\"",
                                        "\"general:motor4_hard\"",
                                        "\"general:motor4_supplier\"",
                                        "\"general:ardrone_name\"",
                                        "\"general:flying_time\"",
                                        "\"general:navdata_demo\"",
                                        "\"general:navdata_options\"",
                                        "\"general:com_watchdog\"",
                                        "\"general:video_enable\"",
                                        "\"general:vision_enable\"",
                                        "\"general:vbat_min\"",
                                        "\"control:accs_offset\"",
                                        "\"control:accs_gains\"",
                                        "\"control:gyros_offset\"",
                                        "\"control:gyros_gains\"",
                                        "\"control:gyros110_offset\"",
                                        "\"control:gyros110_gains\"",
                                        "\"control:magneto_offset\"",
                                        "\"control:magneto_radius\"",
                                        "\"control:gyro_offset_thr_x\"",
                                        "\"control:gyro_offset_thr_y\"",
                                        "\"control:gyro_offset_thr_z\"",
                                        "\"control:pwm_ref_gyros\"",
                                        "\"control:osctun_value\"",
                                        "\"control:osctun_test\"",
                                        "\"control:altitude_max\"",
                                        "\"control:altitude_min\"",
                                        "\"control:control_level\"",
                                        "\"control:euler_angle_max\"",
                                        "\"control:control_iphone_tilt\"",
                                        "\"control:control_vz_max\"",
                                        "\"control:control_yaw\"",
                                        "\"control:outdoor\"",
                                        "\"control:flight_without_shell\"",
                                        "\"control:autonomous_flight\"",
                                        "\"control:manual_trim\"",
                                        "\"control:indoor_euler_angle_max\"",
                                        "\"control:indoor_control_vz_max\"",
                                        "\"control:indoor_control_yaw\"",
                                        "\"control:outdoor_euler_angle_max\"",
                                        "\"control:outdoor_control_vz_max\"",
                                        "\"control:outdoor_control_yaw\"",
                                        "\"control:flying_mode\"",
                                        "\"control:hovering_range\"",
                                        "\"control:flight_anim\"",
                                        "\"network:ssid_single_player\"",
                                        "\"network:ssid_multi_player\"",
                                        "\"network:wifi_mode\"",
                                        "\"network:wifi_rate\"",
                                        "\"network:owner_mac\"",
                                        "\"pic:ultrasound_freq\"",
                                        "\"pic:ultrasound_watchdog\"",
                                        "\"pic:pic_version\"",
                                        "\"video:camif_fps\"",
                                        "\"video:codec_fps\"",
                                        "\"video:camif_buffers\"",
                                        "\"video:num_trackers\"",
                                        "\"video:video_codec\"",
                                        "\"video:video_slices\"",
                                        "\"video:video_live_socket\"",
                                        "\"video:video_storage_space\"",
                                        "\"video:bitrate\"",
                                        "\"video:max_bitrate\"",
                                        "\"video:bitrate_ctrl_mode\"",
                                        "\"video:bitrate_storage\"",
                                        "\"video:video_channel\"",
                                        "\"video:video_on_usb\"",
                                        "\"video:video_file_index\"",
                                        "\"leds:leds_anim\"",
                                        "\"detect:enemy_colors\"",
                                        "\"detect:groundstripe_colors\"",
                                        "\"detect:enemy_without_shell\"",
                                        "\"detect:detect_type\"",
                                        "\"detect:detections_select_h\"",
                                        "\"detect:detections_select_v_hsync\"",
                                        "\"detect:detections_select_v\"",
                                        "\"syslog:output\"",
                                        "\"syslog:max_size\"",
                                        "\"syslog:nb_files\"",
                                        "\"userbox:userbox_cmd\"",
                                        "\"gps:latitude\"",
                                        "\"gps:longitude\"",
                                        "\"gps:altitude\"",
                                        "\"custom:application_id\"",
                                        "\"custom:application_desc\"",
                                        "\"custom:profile_id\"",
                                        "\"custom:profile_desc\"",
                                        "\"custom:session_id\"",
                                        "\"custom:session_desc\""
                                      };
        };
    }
}


#endif // CONFIGCOMMAND_H
